<?php
// Adds ACF fields to Scholarships CPT

// Disable direct file access
if ( ! defined( 'ABSPATH' ) ) {

	exit;

}

// Hide the ACF admin menu item.
add_filter( 'acf/settings/show_admin', '__return_false' );

if( !function_exists('acf_add_local_field_group') ) return;

$scholarship_fields = [
	'key' => 'group_6081927a87194',
	'title' => 'Scholarship Fields',
	'fields' => array(
		array(
			'key' => 'field_60819391df29f',
			'label' => 'Information',
			'name' => 'information',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_6081928ec083c',
			'label' => 'Deadline',
			'name' => 'deadline',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'm/d/Y',
			'first_day' => 0,
		),
		array(
			'key' => 'field_6081930e622e1',
			'label' => 'Amount',
			'name' => 'amount',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6081934bfc85f',
			'label' => 'No. of Awards',
			'name' => 'no_of_awards',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6081937747f53',
			'label' => 'Website',
			'name' => 'website',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_6081943176837',
			'label' => 'Application (Online or Paper)',
			'name' => 'application_online_or_paper',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6081994320573',
			'label' => 'Essays',
			'name' => 'essays',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6081997c73194',
			'label' => 'Letters of Recommendation',
			'name' => 'letters_of_recommendation',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yes' => 'Yes',
				'no' => 'No',
				'varies' => 'Varies',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_60819a58595d7',
			'label' => 'Transcripts',
			'name' => 'transcripts',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6081b972510f5',
			'label' => 'Texas Resident?',
			'name' => 'texas_resident',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 1,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		// array(
		// 	'key' => 'field_6081b995507a2',
		// 	'label' => 'Year in School?',
		// 	'name' => 'year_in_school',
		// 	'type' => 'select',
		// 	'instructions' => '',
		// 	'required' => 1,
		// 	'conditional_logic' => 0,
		// 	'wrapper' => array(
		// 		'width' => '25',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'choices' => array(
		// 		'incoming_freshman' => 'Incoming Freshman',
		// 		'incoming_transfer' => 'Incoming Transfer',
		// 		'entering_transfer' => 'Entering Transfer',
		// 		'externally_selected' => 'Externally Selected',
		// 	),
		// 	'default_value' => array(
		// 	),
		// 	'allow_null' => 0,
		// 	'multiple' => 1,
		// 	'ui' => 0,
		// 	'return_format' => 'value',
		// 	'ajax' => 0,
		// 	'placeholder' => '',
		// ),
		array(
			'key' => 'field_6081c410c5b72',
			'label' => 'Additional Info',
			'name' => 'additional_info',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'utexas_scholarships',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
];

acf_add_local_field_group( $scholarship_fields );
